#!/bin/bash
npm install

gulp --gulpfile gulpstart.js;

bower prune;

bower update --allow-root;

gulp scaffold-init;

# Reflect any removal or renaming of files
gulp clean;

# Get the applications built and into dist
gulp dist-clean --app=blue-ui
