// Generated by CoffeeScript 1.10.0
define(['column-and-block-layout-editor-path/constants'], function(constants) {
  return {
    actionableEvent: function(uiEvent, width, height, offset) {
      var point, xInRange, yInRange, yOffset, yOffsetCap;
      yOffset = constants.DRAG_DROP.SETTINGS.LAYOUT_PASSTHROUGH_PCT;
      yOffsetCap = constants.DRAG_DROP.SETTINGS.LAYOUT_PASSTHROUGH_CAP;
      point = this.getRelativePoint(uiEvent, offset);
      xInRange = this.within(point.x, width);
      yInRange = this.within(point.y, height, yOffset, yOffsetCap);
      return xInRange && yInRange;
    },
    within: function(position, dimension, offset, offsetCap) {
      var dimensionOffset;
      if (offset == null) {
        offset = 0;
      }
      if (offsetCap == null) {
        offsetCap = null;
      }
      dimensionOffset = dimension * offset;
      if (offsetCap) {
        dimensionOffset = Math.min(dimensionOffset, offsetCap);
      }
      return position >= dimensionOffset && position <= dimension - dimensionOffset;
    },
    getRelativeX: function(uiEvent, leftOffset) {
      return Math.round(uiEvent.pageX - leftOffset);
    },
    getRelativeY: function(uiEvent, topOffset) {
      return Math.round(uiEvent.pageY - topOffset);
    },
    getRelativePoint: function(uiEvent, offset) {
      return {
        x: this.getRelativeX(uiEvent, offset.left),
        y: this.getRelativeY(uiEvent, offset.top)
      };
    }
  };
});
