// Generated by CoffeeScript 1.10.0
define(['column-and-block-layout-editor-path/padding/parser'], function(PaddingParser) {
  var PaddingCalculator;
  return PaddingCalculator = (function() {
    function PaddingCalculator(config) {
      this.padding = config.padding;
      this.hasContentLeft = config.hasContentLeft;
      this.hasContentRight = config.hasContentRight;
    }

    PaddingCalculator.calculate = function(config) {
      if (config == null) {
        config = {};
      }
      return new PaddingCalculator(config).calculate();
    };

    PaddingCalculator.prototype.calculate = function() {
      return {
        left: this._getLeftPadding(),
        right: this._getRightPadding()
      };
    };

    PaddingCalculator.prototype._getLeftPadding = function() {
      if (this.hasContentLeft) {
        return Math.floor(this.padding.left / 2);
      } else {
        return this.padding.left;
      }
    };

    PaddingCalculator.prototype._getRightPadding = function() {
      if (this.hasContentRight) {
        return Math.floor(this.padding.right / 2);
      } else {
        return this.padding.right;
      }
    };

    return PaddingCalculator;

  })();
});
