// Generated by CoffeeScript 1.10.0
define(['jquery', 'column-and-block-layout-editor-path/constants'], function($, constants) {
  var PaddingParser;
  return PaddingParser = (function() {
    function PaddingParser(markup) {
      this.$paddingElement = $(markup).find(constants.SELECTORS.PADDING_ELEMENT).addBack(constants.SELECTORS.PADDING_ELEMENT);
    }

    PaddingParser.parse = function(renderedMarkup) {
      return new PaddingParser(renderedMarkup).parse();
    };

    PaddingParser.prototype.parse = function() {
      return {
        left: this._readCss('padding-left'),
        right: this._readCss('padding-right')
      };
    };

    PaddingParser.prototype._readCss = function(attribute) {
      return this._parsePx(this.$paddingElement.css(attribute));
    };

    PaddingParser.prototype._parsePx = function(pxString) {
      return parseInt(pxString, 10) || 0;
    };

    return PaddingParser;

  })();
});
