// Generated by CoffeeScript 1.10.0
define(['jquery', 'column-and-block-layout-editor-path/constants'], function($, constants) {
  var PaddingRenderer;
  return PaddingRenderer = (function() {
    function PaddingRenderer(config) {
      this.markup = config.markup;
      this.padding = config.padding;
    }

    PaddingRenderer.render = function(config) {
      if (config == null) {
        config = {};
      }
      return new PaddingRenderer(config).render();
    };

    PaddingRenderer.prototype.render = function() {
      var $markup, $paddingElement;
      $markup = $(this.markup);
      $paddingElement = this._getPaddingElement($markup);
      $paddingElement.css('padding-left', this.padding.left);
      $paddingElement.css('padding-right', this.padding.right);
      return $markup.prop('outerHTML');
    };

    PaddingRenderer.prototype._getPaddingElement = function($markup) {
      return $markup.find(constants.SELECTORS.PADDING_ELEMENT).addBack(constants.SELECTORS.PADDING_ELEMENT);
    };

    return PaddingRenderer;

  })();
});
